import type { DocPageMetadata, DocSearchEntry } from "./types";

export const DOC_PAGES: Record<string, DocPageMetadata> = {
  "what-is-flatron": {
    slug: "what-is-flatron",
    title: "What is Flatron?",
    description:
      "A CLI-first scaffolding toolkit with a visual configuration platform for generating and extending production-oriented .NET applications.",
    section: "Getting Started",
    order: 1,
    toc: [
      { id: "overview", title: "Overview", level: 2 },
      { id: "what-flatron-is-and-is-not", title: "What Flatron Is & Is Not", level: 2 },
      { id: "cli-and-platform-relationship", title: "Platform & CLI Relationship", level: 2 },
      { id: "generated-output", title: "Generated Architecture", level: 2 },
      { id: "key-benefits", title: "Key Principles", level: 2 },
    ],
    next: { title: "Who is Flatron For?", href: "/docs/who-is-flatron-for" },
    keywords: [
      "what is flatron",
      "scaffolding",
      "clean architecture",
      "dotnet 10",
      "code generator",
      "cli",
      "visual builder",
      "zero lock-in",
    ],
  },
  "who-is-flatron-for": {
    slug: "who-is-flatron-for",
    title: "Who is Flatron For?",
    description:
      "Understand the target audience, ideal project scenarios, and when Flatron is—and is not—the right tool for your team.",
    section: "Getting Started",
    order: 2,
    toc: [
      { id: "ideal-audiences", title: "Ideal Audiences", level: 2 },
      { id: "target-scenarios", title: "Target Use Cases", level: 2 },
      { id: "who-it-is-not-for", title: "When Not to Use Flatron", level: 2 },
    ],
    previous: { title: "What is Flatron?", href: "/docs/what-is-flatron" },
    next: { title: "Quick Start", href: "/docs/quick-start" },
    keywords: [
      "who is flatron for",
      "target developers",
      "full stack teams",
      "dotnet teams",
      "react angular",
      "use cases",
    ],
  },
  "quick-start": {
    slug: "quick-start",
    title: "Quick Start",
    description:
      "Get up and running with Flatron in five minutes: scaffold your first solution, run the app, and generate a domain feature.",
    section: "Getting Started",
    order: 3,
    toc: [
      { id: "prerequisites", title: "Prerequisites", level: 2 },
      { id: "step-1-scaffold", title: "1. Scaffold a Solution", level: 2 },
      { id: "step-2-enter-workspace", title: "2. Enter Workspace", level: 2 },
      { id: "step-3-run-app", title: "3. Run Backend & Frontend", level: 2 },
      { id: "step-4-create-feature", title: "4. Create a Domain Feature", level: 2 },
      { id: "step-5-install-module", title: "5. Install an Application Module", level: 2 },
    ],
    previous: { title: "Who is Flatron For?", href: "/docs/who-is-flatron-for" },
    next: { title: "How Flatron Works", href: "/docs/how-flatron-works" },
    keywords: [
      "quick start",
      "getting started",
      "npx flatron",
      "flatron create feature",
      "flatron create module",
      "installation",
    ],
  },
  "how-flatron-works": {
    slug: "how-flatron-works",
    title: "How Flatron Works",
    description:
      "Understand the mental model of Flatron: from interactive blueprinting and CLI execution to progressive feature and module expansion.",
    section: "Getting Started",
    order: 4,
    toc: [
      { id: "mental-model", title: "The Flatron Mental Model", level: 2 },
      { id: "execution-lifecycle", title: "The 3-Stage Lifecycle", level: 2 },
      { id: "manifest-system", title: "Stack Manifest (.fullstack-app.json)", level: 2 },
      { id: "progressive-expansion", title: "Progressive Feature & Module Growth", level: 2 },
    ],
    previous: { title: "Quick Start", href: "/docs/quick-start" },
    next: { title: "Stack Builder", href: "/docs/stack-builder" },
    keywords: [
      "how flatron works",
      "mental model",
      "lifecycle",
      "blueprint",
      "manifest",
      "progressive expansion",
    ],
  },
  "stack-builder": {
    slug: "stack-builder",
    title: "Stack Builder",
    description:
      "Configure full-stack architecture, backend ORM, presentation models, database engines, authentication, and frontend tooling with verified compatibility.",
    section: "Core Concepts",
    order: 5,
    toc: [
      { id: "overview", title: "Overview", level: 2 },
      { id: "project-scope", title: "Project Scope & Presentation", level: 2 },
      { id: "backend-options", title: "Backend Architecture & Data", level: 2 },
      { id: "frontend-options", title: "Frontend Frameworks & Tooling", level: 2 },
      { id: "compatibility-rules", title: "Compatibility Constraints", level: 2 },
      { id: "builder-outputs", title: "Builder Outputs", level: 2 },
    ],
    previous: { title: "How Flatron Works", href: "/docs/how-flatron-works" },
    next: { title: "Feature Builder", href: "/docs/feature-builder" },
    keywords: [
      "stack builder",
      "architecture",
      "presentation rules",
      "controllers",
      "minimal api",
      "ef core",
      "dapper",
      "react",
      "angular",
      "compatibility",
    ],
  },
  "feature-builder": {
    slug: "feature-builder",
    title: "Feature Builder",
    description:
      "Scaffold end-to-end domain business entities with CQRS handlers, validation, typed fields, relationships, enums, media, and frontend dialogs.",
    section: "Core Concepts",
    order: 6,
    toc: [
      { id: "what-is-a-feature", title: "What is a Feature?", level: 2 },
      { id: "configurable-capabilities", title: "Configurable Capabilities", level: 2 },
      { id: "field-types-and-rules", title: "Supported Field Types & Rules", level: 2 },
      { id: "concrete-example", title: "Concrete Example: Product Feature", level: 2 },
      { id: "cli-generation", title: "CLI Command Format", level: 2 },
    ],
    previous: { title: "Stack Builder", href: "/docs/stack-builder" },
    next: { title: "Modules", href: "/docs/modules" },
    keywords: [
      "feature builder",
      "domain entity",
      "cqrs",
      "mediatr",
      "crud",
      "enums",
      "relationships",
      "fields",
      "flatron create feature",
    ],
  },
  "modules": {
    slug: "modules",
    title: "Modules",
    description:
      "Explore the 8 pre-wired enterprise application modules: Authentication, User Management, Permissions, Audit Trail, Notifications, Localization, Rich Text, and Dashboard Foundation.",
    section: "Core Concepts",
    order: 7,
    toc: [
      { id: "what-is-a-module", title: "What is a Module?", level: 2 },
      { id: "the-8-available-modules", title: "The 8 Available Modules", level: 2 },
      { id: "module-dependencies", title: "Module Dependencies & Requirements", level: 2 },
      { id: "installing-modules", title: "Installing Modules via CLI", level: 2 },
    ],
    previous: { title: "Feature Builder", href: "/docs/feature-builder" },
    next: { title: "Feature vs Module", href: "/docs/feature-vs-module" },
    keywords: [
      "modules",
      "auth",
      "users",
      "permissions",
      "audit trail",
      "notifications",
      "localization",
      "rich text",
      "dashboard",
      "flatron create module",
    ],
  },
  "feature-vs-module": {
    slug: "feature-vs-module",
    title: "Feature vs Module",
    description:
      "The critical distinction: when to scaffold a domain business Feature versus when to install a reusable application Module.",
    section: "Core Concepts",
    order: 8,
    toc: [
      { id: "the-core-mental-model", title: "The Core Mental Model", level: 2 },
      { id: "comparison-matrix", title: "Comparison Matrix", level: 2 },
      { id: "decision-guide", title: "Decision Guide: Feature or Module?", level: 2 },
      { id: "real-world-example", title: "Real-World Architecture Example", level: 2 },
    ],
    previous: { title: "Modules", href: "/docs/modules" },
    keywords: [
      "feature vs module",
      "domain vs infrastructure",
      "when to use",
      "decision matrix",
      "architecture guide",
    ],
  },
};

export const DOC_SECTIONS = [
  {
    title: "Getting Started",
    pages: [
      DOC_PAGES["what-is-flatron"],
      DOC_PAGES["who-is-flatron-for"],
      DOC_PAGES["quick-start"],
      DOC_PAGES["how-flatron-works"],
    ],
  },
  {
    title: "Core Concepts",
    pages: [
      DOC_PAGES["stack-builder"],
      DOC_PAGES["feature-builder"],
      DOC_PAGES["modules"],
      DOC_PAGES["feature-vs-module"],
    ],
  },
];

export const DOC_SEARCH_INDEX: DocSearchEntry[] = Object.values(DOC_PAGES).map(
  (page) => ({
    slug: page.slug,
    href: `/docs/${page.slug}`,
    title: page.title,
    description: page.description,
    section: page.section,
    keywords: page.keywords,
    headings: page.toc.map((t) => t.title),
  }),
);
